README.md
Utilities.Audio/Packages/com.utilities.audio/Documentation~/README.md
Utilities.Audio/Packages/com.utilities.audio/Runtime/AbstractRecordingBehaviour.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/IEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- fixed missing script changes
- fixed readme docs

com.utilities.audio 1.0.0-preview.2

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/AudioClipExtensions.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMFormatSize.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMFormatSize.cs.meta
Utilities.Audio/Packages/com.utilities.audio/package.json

com.utilities.audio 1.0.0-preview.4

---

README.md
Utilities.Audio/Packages/com.utilities.audio/Documentation~/README.md
Utilities.Audio/Packages/com.utilities.audio/Runtime/AbstractRecordingBehaviour.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- added additional debug and recording location options to AbstractRecordingBehaviour
- updated docs

com.utilities.audio 1.0.1

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/Microphone.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- Fixed some more webgl build errors

com.utilities.audio 1.0.3

---

Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/Packages/manifest.json
Utilities.Audio/ProjectSettings/ProjectVersion.txt

com.utilities.audio 1.0.4

---

Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/Packages/manifest.json
Utilities.Audio/ProjectSettings/ProjectSettings.asset
Utilities.Audio/ProjectSettings/ProjectVersion.txt
Utilities.Audio/ProjectSettings/UnityConnectSettings.asset

com.utilities.audio 1.0.6

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/RecordingManager.cs
Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/Packages/manifest.json
Utilities.Audio/ProjectSettings/ProjectVersion.txt

- fixed NRE when throwing exception on background thread
- bumped deps

com.utilities.audio 1.0.7

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/AudioClipExtensions.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs.meta
Utilities.Audio/Packages/com.utilities.audio/package.json

- Added PCMEncoder class for easier sample conversion

com.utilities.audio 1.0.8

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

com.utilities.audio 1.0.9

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- fix some issues with pcm encode/decode

com.utilities.audio 1.0.10

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMFormatSize.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- added 24 and 32 bit pcm format support

com.utilities.audio 1.0.11

---

README.md
Utilities.Audio/Packages/com.utilities.audio/Documentation~/README.md
Utilities.Audio/Packages/com.utilities.audio/Runtime/AbstractRecordingBehaviour.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/RecordingManager.cs
Utilities.Audio/Packages/com.utilities.audio/Tests.meta
Utilities.Audio/Packages/com.utilities.audio/Tests/AssemblyInfo.cs.meta
Utilities.Audio/Packages/com.utilities.audio/Tests/TestFixture_01_PCM_Encoding.cs
Utilities.Audio/Packages/com.utilities.audio/Tests/TestFixture_01_PCM_Encoding.cs.meta
Utilities.Audio/Packages/com.utilities.audio/Tests/TestUtilities.cs
Utilities.Audio/Packages/com.utilities.audio/Tests/TestUtilities.cs.meta
Utilities.Audio/Packages/com.utilities.audio/Tests/Utilities.AudioTests.asmdef
Utilities.Audio/Packages/com.utilities.audio/Tests/Utilities.AudioTests.asmdef.meta
Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/Packages/manifest.json
Utilities.Audio/ProjectSettings/ProjectVersion.txt

- Updated PCM Encoder
- Added default recording device property to RecordingManager
- Added unit tests
- Updated docs

com.utilities.audio 1.0.12

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/RecordingManager.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- Fixed MicrophoneManager.StartRecording callback context to return on main thread.

com.utilities.audio 1.1.1

---

.github/workflows/upm-subtree-split.yml
README.md
Utilities.Audio/Packages/com.utilities.audio/Documentation~/README.md
Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/ProjectSettings/ProjectVersion.txt

- com.utilities.async -> 2.1.2
- updated workflows
- updated docs
- updated editor to 2022.3.16 LTS

com.utilities.audio 1.1.2

---

.github/workflows/upm-subtree-split.yml
Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/Packages/manifest.json

- updated com.utilities.async -> 2.1.3

com.utilities.audio 1.1.3

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/AbstractRecordingBehaviour.cs
Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/ProjectSettings/ProjectVersion.txt

- Fix backwards compatibility with 2021.3 LTS

com.utilities.audio 1.2.1

---

.github/workflows/unity.yml
Utilities.Audio/Assets/empty.unity
Utilities.Audio/Assets/empty.unity.meta
Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/Packages/manifest.json
Utilities.Audio/ProjectSettings/EditorBuildSettings.asset
Utilities.Audio/ProjectSettings/ProjectSettings.asset
Utilities.Audio/ProjectSettings/ProjectVersion.txt

- com.utilities.async -> 2.1.7

com.utilities.audio 1.2.2

---

.github/workflows/unity.yml
Utilities.Audio/Packages/com.utilities.audio/Runtime/Plugins/WebGL/UnityMicrophoneLibrary.jslib
Utilities.Audio/Packages/com.utilities.audio/Runtime/Plugins/WebGL/UnityMicrophoneLibrary.jspre
Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/Packages/manifest.json
Utilities.Audio/ProjectSettings/ProjectVersion.txt

- updated [unity 6 support](https://docs.unity3d.com/6000.0/Documentation/Manual/web-interacting-browser-deprecated.html)

com.utilities.audio 1.2.3

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/IEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/RecordingManager.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- hotfix to include missing changes for 2.0.0 release

com.utilities.audio 2.0.1

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/Plugins/WebGL/UnityAudioLibrary.jslib
Utilities.Audio/Packages/com.utilities.audio/Runtime/RecordingManager.cs
Utilities.Audio/Packages/com.utilities.audio/Runtime/StreamAudioSource.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- added StreamAudioSource.IsEmpty
- added implicit operator to StreamAudioSource to access AudioSource
- try to wait for available microphone devices when recording is started
- resize pcmData array when decoding audio that doesn't match the bit depth

com.utilities.audio 2.2.1

---

.github/workflows/unity.yml
Utilities.Audio/Packages/com.utilities.audio/package.json

- updated com.utilities.async -> 2.2.2
- updated workflows

com.utilities.audio 2.2.2

---

.gitignore
Utilities.Audio/Packages/com.utilities.audio/Runtime/PCMEncoder.cs
Utilities.Audio/Packages/com.utilities.audio/Tests/TestFixture_01_PCM_Encoding.cs
Utilities.Audio/Packages/com.utilities.audio/package.json
Utilities.Audio/Packages/manifest.json

- updated PCMEncoder linear interpolation to improve audio quality

com.utilities.audio 2.2.3

---

Utilities.Audio/Packages/com.utilities.audio/Runtime/StreamAudioSource.cs
Utilities.Audio/Packages/com.utilities.audio/package.json

- Add `StreamAudioSource.ClearBuffer` to clear any pending buffer data in the playback queue.

com.utilities.audio 2.2.4

---

.github/workflows/unity.yml
.github/workflows/upm-subtree-split.yml
Utilities.Audio/Packages/com.utilities.audio/package.json

com.utilities.audio 2.2.6
